# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170417_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 4, 18, 11, 44, 16, 404171, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
